env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

rules:
  indent: [1, 4, {"SwitchCase": 1}]
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - single
  comma-dangle:
    - off
  no-console:
    - warn
  no-unused-vars:
    - warn
  no-undef:
    - warn